version: '3'
services:
  nginx:
   container_name: some-nginx
   image: nginx:1.13
   restart: always
   ports:
   #- 81:80
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
   - ./app/amnesia-lin/app:/usr/share/nginx/html/
   depends_on:
   - app

  app:
    restart: always
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "8181:8181"
    command: java -jar -Xms1024m -Xmx4096m -Dorg.eclipse.jetty.server.Request.maxFormKeys=1000000 -Dorg.eclipse.jetty.server.Request.maxFormContentSize=1000000 /amnesia-lin/amnesiaBackEnd-1.0-SNAPSHOT.jar --server.port=8181 --trace
