FROM openjdk:8
ADD /amnesia-lin/ /amnesia-lin/
#ENTRYPOINT ["java", "-jar", "-Xms1024m", "-Xmx4096m", "-Dorg.eclipse.jetty.server.Request.maxFormKeys=1000000", "-Dorg.eclipse.jetty.server.Request.maxFormContentSize=1000000", "/amnesia-lin/amnesiaBackEnd-1.0-SNAPSHOT.jar", "--server.port=8181", "--trace"]
#CMD ["java","-version"]
